name: biasloss
channels:
  - defaults
  - pytorch
dependencies:
  - seaborn=0.10.1
  - scipy=1.4.1
  - numpy=1.18.1
  - pillow=7.1.2
  - matplotlib=3.1.3
  - cudatoolkit=10.1
  - pytorch=1.5.0
  - torchvision=0.6.0
  - scikit-image
